export const CHANGE_SEARCHTEXT = 'CHANGE_SEARCHTEXT';
export const CHANGE_FAVORITES = 'CHANGE_FAVORITES';
export const REMOVE_FROM_FAVORITES = 'REMOVE_FROM_FAVORITES';

export const GET_PICTURES_REQUEST = 'GET_PICTURES_REQUEST';
export const GET_PICTURES_REQUEST_SUCCESS = 'GET_PICTURES_REQUEST_SUCCESS';
export const GET_PICTURES_REQUEST_FAIL = 'GET_PICTURES_REQUEST_FAIL';

export const GET_PICTURE_BY_ID_REQUEST = 'GET_PICTURE_BY_ID_REQUEST';
export const GET_PICTURE_BY_ID_REQUEST_SUCCESS = 'GET_PICTURE_BY_ID_REQUEST_SUCCESS';
export const GET_PICTURE_BY_ID_REQUEST_FAIL = 'GET_PICTURE_BY_ID_REQUEST_FAIL';

export const GET_INFO_BY_ID_REQUEST = 'GET_INFO_BY_ID_REQUEST';
export const GET_INFO_BY_ID_REQUEST_SUCCESS = 'GET_INFO_BY_ID_REQUEST_SUCCESS';
export const GET_INFO_BY_ID_REQUEST_FAIL = 'GET_INFO_BY_ID_REQUEST_FAIL';

export const GET_RECENT_PHOTO_REQUEST = 'GET_RECENT_PHOTO_REQUEST';
export const GET_RECENT_PHOTO_REQUEST_SUCCESS = 'GET_RECENT_PHOTO_REQUEST_SUCCESS';
export const GET_RECENT_PHOTO_REQUEST_FAIL = 'GET_RECENT_PHOTO_REQUEST_FAIL';
